version: "3.7"

volumes:
  node_modules:

services:
  backend:
    container_name: backend
    volumes:
      - ./backend:/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    network_mode: host
    environment:
       TZ=Asia/Singapore
