version: "3.7"

volumes:
  node_modules:

services:

  gateway-envoy:
    container_name: envoy
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

  client:
    container_name: client
    volumes:
          - ./client:/client
          - node_modules:/client/node_modules
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


  backend:
    container_name: backend
    volumes:
          - ./backend:/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"


  telebot:
    container_name: telebot
    environment:
        PYTHONUNBUFFERED: 1
    volumes:
      - ./telebot:/telebot
    build:
      context: ./telebot
      dockerfile: Dockerfile
    ports:
      - "9091:9091"

  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8070:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard