# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iot_prototype.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13iot_prototype.proto\x12\x0egate_prototype\"\x12\n\x04Gate\x12\n\n\x02id\x18\x01 \x01(\x03\"\x8c\x01\n\tGateState\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x35\n\x05state\x18\x02 \x01(\x0e\x32&.gate_prototype.GateState.GatePosition\"<\n\x0cGatePosition\x12\n\n\x06\x43LOSED\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x0b\n\x07INITIAL\x10\x03\"\x17\n\tFireAlarm\x12\n\n\x02id\x18\x01 \x01(\x03\"\x80\x01\n\x0e\x46ireAlarmState\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x38\n\x05state\x18\x02 \x01(\x0e\x32).gate_prototype.FireAlarmState.AlarmState\"(\n\nAlarmState\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32\x81\x02\n\x1aIotControlPrototypeService\x12\x43\n\x0cGetGateState\x12\x14.gate_prototype.Gate\x1a\x19.gate_prototype.GateState\"\x00\x30\x01\x12J\n\x0cSetGateState\x12\x19.gate_prototype.GateState\x1a\x19.gate_prototype.GateState\"\x00(\x01\x30\x01\x12R\n\x11GetFireAlarmState\x12\x19.gate_prototype.FireAlarm\x1a\x1e.gate_prototype.FireAlarmState\"\x00\x30\x01\x62\x06proto3')



_GATE = DESCRIPTOR.message_types_by_name['Gate']
_GATESTATE = DESCRIPTOR.message_types_by_name['GateState']
_FIREALARM = DESCRIPTOR.message_types_by_name['FireAlarm']
_FIREALARMSTATE = DESCRIPTOR.message_types_by_name['FireAlarmState']
_GATESTATE_GATEPOSITION = _GATESTATE.enum_types_by_name['GatePosition']
_FIREALARMSTATE_ALARMSTATE = _FIREALARMSTATE.enum_types_by_name['AlarmState']
Gate = _reflection.GeneratedProtocolMessageType('Gate', (_message.Message,), {
  'DESCRIPTOR' : _GATE,
  '__module__' : 'iot_prototype_pb2'
  # @@protoc_insertion_point(class_scope:gate_prototype.Gate)
  })
_sym_db.RegisterMessage(Gate)

GateState = _reflection.GeneratedProtocolMessageType('GateState', (_message.Message,), {
  'DESCRIPTOR' : _GATESTATE,
  '__module__' : 'iot_prototype_pb2'
  # @@protoc_insertion_point(class_scope:gate_prototype.GateState)
  })
_sym_db.RegisterMessage(GateState)

FireAlarm = _reflection.GeneratedProtocolMessageType('FireAlarm', (_message.Message,), {
  'DESCRIPTOR' : _FIREALARM,
  '__module__' : 'iot_prototype_pb2'
  # @@protoc_insertion_point(class_scope:gate_prototype.FireAlarm)
  })
_sym_db.RegisterMessage(FireAlarm)

FireAlarmState = _reflection.GeneratedProtocolMessageType('FireAlarmState', (_message.Message,), {
  'DESCRIPTOR' : _FIREALARMSTATE,
  '__module__' : 'iot_prototype_pb2'
  # @@protoc_insertion_point(class_scope:gate_prototype.FireAlarmState)
  })
_sym_db.RegisterMessage(FireAlarmState)

_IOTCONTROLPROTOTYPESERVICE = DESCRIPTOR.services_by_name['IotControlPrototypeService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GATE._serialized_start=39
  _GATE._serialized_end=57
  _GATESTATE._serialized_start=60
  _GATESTATE._serialized_end=200
  _GATESTATE_GATEPOSITION._serialized_start=140
  _GATESTATE_GATEPOSITION._serialized_end=200
  _FIREALARM._serialized_start=202
  _FIREALARM._serialized_end=225
  _FIREALARMSTATE._serialized_start=228
  _FIREALARMSTATE._serialized_end=356
  _FIREALARMSTATE_ALARMSTATE._serialized_start=316
  _FIREALARMSTATE_ALARMSTATE._serialized_end=356
  _IOTCONTROLPROTOTYPESERVICE._serialized_start=359
  _IOTCONTROLPROTOTYPESERVICE._serialized_end=616
# @@protoc_insertion_point(module_scope)
