"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import http_webapp_pb2
import operations_ecosys_pb2

class WebAppServicesStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    GetRosterAssignmentsForWebApp: grpc.UnaryUnaryMultiCallable[
        http_webapp_pb2.HTTPRosterMessage,
        http_webapp_pb2.HTTPMessage]
    """<><> Telegram WebApp - HTTP <><>"""

    PostWReportFromWebApp: grpc.UnaryUnaryMultiCallable[
        operations_ecosys_pb2.IncidentReport,
        http_webapp_pb2.HTTPMessage]
    """rpc PostWReportFromWebApp(HTTPMessage) returns (HTTPMessage) {
        option (google.api.http) = {
            post: "/http/post_report"
            body: "*"
        };
    }

    """


class WebAppServicesServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetRosterAssignmentsForWebApp(self,
        request: http_webapp_pb2.HTTPRosterMessage,
        context: grpc.ServicerContext,
    ) -> http_webapp_pb2.HTTPMessage:
        """<><> Telegram WebApp - HTTP <><>"""
        pass

    @abc.abstractmethod
    def PostWReportFromWebApp(self,
        request: operations_ecosys_pb2.IncidentReport,
        context: grpc.ServicerContext,
    ) -> http_webapp_pb2.HTTPMessage:
        """rpc PostWReportFromWebApp(HTTPMessage) returns (HTTPMessage) {
            option (google.api.http) = {
                post: "/http/post_report"
                body: "*"
            };
        }

        """
        pass


def add_WebAppServicesServicer_to_server(servicer: WebAppServicesServicer, server: grpc.Server) -> None: ...
